usuarios/urls.py
from django.urls import path

from .views import CrearUsuarioView, ActualizarUsuarioView, ListarUsuarioView

app_name = 'gestion_usuarios'

urlpatterns = [
    path('listar', ListarUsuarioView.as_view(), name='listar_usuario'),
    path('crear', CrearUsuarioView.as_view(), name='crear_usuario'),
    path('actualizar/<str:pk>', ActualizarUsuarioView.as_view(), name='actualizar_usuario'),
]

usuarios_django/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from usuarios.views import IndexView

urlpatterns = [
    path('', IndexView.as_view(),name='index'),
    path('admin/', admin.site.urls),
    path('usuarios/', include('usuarios.urls', namespace='usuarios')),
    path('login', auth_views.LoginView.as_view(), name='login'),
    path('logout', auth_views.LogoutView.as_view(next_page='index') , name='logout'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

usuarios/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.core.validators import FileExtensionValidator
# Create your models here.


class Usuario(AbstractUser):
    pdf_file = models.FileField(validators=[FileExtensionValidator(allowed_extensions=['pdf'])], null=True, blank=True)
    pdf_file_2 = models.FileField(validators=[FileExtensionValidator(allowed_extensions=['pdf'])], null=True,
                                  blank=True)

    class Meta:
        permissions = (
            ('add_auditoria', 'Puede consultar la auditoría del sistema'),
        )

usuarios/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, UsernameField

from usuarios.models import Usuario


class CrearUsuarioForm(UserCreationForm):
    first_name = forms.CharField(max_length=140, required=True)
    last_name = forms.CharField(max_length=140, required=False)
    email = forms.EmailField(required=True)

    class Meta:
        model = Usuario
        fields = (
            'username',
            'email',
            'first_name',
            'last_name',
            'is_staff',
            'password1',
            'password2',
        )


class EditarUsuarioForm(forms.ModelForm):
    class Meta:
        model = Usuario
        fields = (
            'username',
            'email',
            'first_name',
            'last_name',
            'is_active',
            'is_staff',
            'pdf_file',
            'pdf_file_2'
        )
        field_classes = {'username': UsernameField}

usuarios/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.shortcuts import render

# Create your views here.
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, TemplateView, ListView

from usuarios.forms import CrearUsuarioForm, EditarUsuarioForm
from usuarios.models import Usuario


class StaffRequiredMixin(LoginRequiredMixin, UserPassesTestMixin):
    login_url = reverse_lazy('index')

    def test_func(self):
        return self.request.user.is_staff


class IndexView(TemplateView):
    template_name = 'index.html'


class CrearUsuarioView(StaffRequiredMixin, CreateView):
    model = Usuario
    form_class = CrearUsuarioForm
    success_url = reverse_lazy('usuarios:listar_usuario')


class ActualizarUsuarioView(StaffRequiredMixin, UpdateView):
    model = Usuario
    form_class = EditarUsuarioForm
    success_url = reverse_lazy('usuarios:listar_usuario')


class ListarUsuarioView(StaffRequiredMixin, ListView):
    model = Usuario

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block titulo_pagina %} {% endblock %}</title>

    <!-- ================= Favicon ================== -->
    <!-- Standard -->
    <link rel="shortcut icon" href="http://placehold.it/64.png/000/fff">
    <!-- Retina iPad Touch Icon-->
    <link rel="apple-touch-icon" sizes="144x144" href="http://placehold.it/144.png/000/fff">
    <!-- Retina iPhone Touch Icon-->
    <link rel="apple-touch-icon" sizes="114x114" href="http://placehold.it/114.png/000/fff">
    <!-- Standard iPad Touch Icon-->
    <link rel="apple-touch-icon" sizes="72x72" href="http://placehold.it/72.png/000/fff">
    <!-- Standard iPhone Touch Icon-->
    <link rel="apple-touch-icon" sizes="57x57" href="http://placehold.it/57.png/000/fff">

    <!-- Toastr -->
    <link href="{% static 'assets/css/lib/toastr/toastr.min.css' %}" rel="stylesheet">

    <!-- Datatable -->
    <link href="{% static 'assets/css/lib/datatable/dataTables.bootstrap.min.css' %}" rel="stylesheet" />
    <link href="{% static 'assets/css/lib/data-table/buttons.bootstrap.min.css' %}" rel="stylesheet" />

    <!-- Select2 -->
    <link href="{% static 'assets/css/lib/select2/select2.min.css' %}" rel="stylesheet">


    <!-- Common -->
    <link href="{% static 'assets/css/lib/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/css/lib/themify-icons.css' %}" rel="stylesheet">
    <link href="{% static 'assets/css/lib/menubar/sidebar.css' %}" rel="stylesheet">
    <link href="{% static 'assets/css/lib/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/css/lib/helper.css' %}" rel="stylesheet">
    <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">
    {% block css %}
    {% endblock %}
</head>

<body>

    <div class="sidebar sidebar-hide-to-small sidebar-shrink sidebar-gestures">
        <div class="nano">
            <div class="nano-content">
                <div class="logo">
                    <a href="index.html">
                        <!-- <img src="assets/images/logo.png" alt="" /> -->
                        <span>Usuarios django</span>
                    </a>
                </div>
                <ul>
                    {% include 'menu.html' %}
                </ul>
            </div>
        </div>
    </div>
    <!-- /# sidebar -->


    <div class="header">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <div class="float-left">
                        <div class="hamburger sidebar-toggle">
                            <span class="line"></span>
                            <span class="line"></span>
                            <span class="line"></span>
                        </div>
                    </div>
                    <div class="float-right">


                        <div class="dropdown dib">
                            {% if user.is_authenticated %}
                            <div class="header-icon" data-toggle="dropdown">
                                <span class="user-avatar">{{ user }}
                                    <i class="ti-angle-down f-s-10"></i>
                                </span>
                                <div class="drop-down dropdown-profile dropdown-menu dropdown-menu-right">
                                    <div class="dropdown-content-body">
                                        <div class="dropdown-content-heading">
                                        <span class="text-left">Email</span>
                                        <p >{{ user.email }}</p>
                                    </div>

                                    </div>
                                </div>
                            </div>{% endif %}
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>



    <div class="content-wrap">
        <div class="main">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-8 p-r-0 title-margin-right">
                        <div class="page-header">
                            <div class="page-title">
                                <h1>{% block titulo %}Hello,
                                    <span>Welcome Here</span>
                                {% endblock %}</h1>
                            </div>
                        </div>
                    </div>
                    <!-- /# column -->
                    <div class="col-lg-4 p-l-0 title-margin-left">
                        <div class="page-header">
                            <div class="page-title">
                                <ol class="breadcrumb">
                                    {% block migapan %}
                                    <li class="breadcrumb-item">
                                        <a href="#">Dashboard</a>
                                    </li>
                                    <li class="breadcrumb-item active">UI-Blank</li>
                                    {% endblock %}
                                </ol>
                            </div>
                        </div>
                    </div>
                    <!-- /# column -->
                </div>
                <!-- /# row -->
                <section id="main-content">
                    {% block contenido %}{% endblock %}
                    <div class="row">
                        <div class="col-lg-12">
                            <div id="extra-area-chart"></div>
                            <div id="morris-line-chart"></div>
                            <div class="footer">
                                <p>2021 © DANIEL DHA.

                                </p>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
        </div>
    </div>




    <!-- Common -->
    <script src="{% static 'assets/js/lib/jquery.min.js' %}"></script>
    <script src="{% static 'assets/js/lib/jquery.nanoscroller.min.js' %}"></script>
    <script src="{% static 'assets/js/lib/menubar/sidebar.js' %}"></script>
    <script src="{% static 'assets/js/lib/preloader/pace.min.js' %}"></script>
    <script src="{% static 'assets/js/lib/bootstrap.min.js' %}"></script>
    <script src="{% static 'assets/js/scripts.js' %}"></script>

    <!-- Select2 -->
    <script src="{% static 'assets/js/lib/select2/select2.full.min.js' %}"></script>


    <!-- Datatable -->
    <script src="{% static 'assets/js/lib/data-table/datatables.min.js' %}"></script>
    <script src="{% static 'assets/js/lib/data-table/buttons.dataTables.min.js' %}"></script>
    <script src="{% static 'assets/js/lib/data-table/dataTables.buttons.min.js' %}"></script>
    <script src="{% static 'assets/js/lib/data-table/buttons.flash.min.js' %}"></script>
    <script src="{% static 'assets/js/lib/data-table/jszip.min.js' %}"></script>
    <script src="{% static 'assets/js/lib/data-table/pdfmake.min.js' %}"></script>
    <script src="{% static 'assets/js/lib/data-table/vfs_fonts.js' %}"></script>
    <script src="{% static 'assets/js/lib/data-table/buttons.html5.min.js' %}"></script>
    <script src="{% static 'assets/js/lib/data-table/buttons.print.min.js' %}"></script>
    <script src="{% static 'assets/js/lib/data-table/datatables-init.js' %}"></script>



    <!-- Toastr -->
    <script src="{% static 'assets/js/lib/toastr/toastr.min.js' %}"></script>
    <script src="{% static 'assets/js/lib/toastr/toastr.init.js' %}"></script>

    {% block js %}{% endblock %}


</body>

</html>

templates/index.html
{% extends 'base.html' %}
{% block titulo %}
    Hola, Bienvenido
{% endblock %}
{% block contenido %}
    {% if user.is_authenticated %}
        <div class="row">
        <div class="col-lg-6">
            <div class="card">
                <div class="card-title">
                    <h4>Bienvenido a usuarios en django</h4>

                </div>
                <div class="card-body">
                    <div class="basic-form">
                        {% if user.is_staff %}
                            <p> Eres un administrador</p>
                        {% else %}
                            <p> Eres un cliente</p>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
        <!-- /# column -->

    </div>
    {% else %}
        <a href="{% url 'login' %}" class="btn btn-primary">Ingresar</a>
    {% endif %}
{% endblock %}

templates/menu.html
{% if user.is_staff %}
    <li class="label">Administrador</li>
    <li>
        <a class="sidebar-sub-toggle">
            <i class="ti-home"></i> Ususarios
            <span class="badge badge-primary">2</span>
            <span class="sidebar-collapse-icon ti-angle-down"></span>
        </a>
        <ul>
            <li>
                <a href="{% url 'usuarios:listar_usuario' %}">Listar usuarios</a>
            </li>
            <li>
                <a href="{% url 'usuarios:crear_usuario' %}">Crear usuarios</a>
            </li>


        </ul>
    </li>{% endif %}

<li>
    <a href="{% url 'logout' %}">
        <i class="ti-close"></i> Logout</a>
</li>

templates/usuarios/usuario_form.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block titulo %}
    {% if object %}
        Editar
    {% else %}
        Crear
    {% endif %} Usuario
{% endblock %}
{% block contenido %}
    <div class="row">
        <div class="col-lg-6">
            <div class="card">
                <div class="card-title">
                    <h4>Formiulario de Usuario</h4>

                </div>
                <div class="card-body">
                    <div class="basic-form">
                        {% bootstrap_form_errors form %}
                        <form method="post" action="" enctype="multipart/form-data" class="margin-bottom-0">
                            {% csrf_token %}
                            {% bootstrap_form form layout='inline' %}
                            <div class="login-buttons">
                                <button type="submit" class="btn btn-primary btn-block btn-lg">
                                    {% if object %}
                                        <i class="fa fa-edit"></i> Editar
                                    {% else %}
                                        <i class="fa fa-plus"></i> Crear
                                    {% endif %}
                                </button>
                            </div>

                        </form>
                    </div>
                </div>
            </div>
        </div>
        <!-- /# column -->

    </div>

{% endblock %}

templates/usuarios/usuario_list.html
{% extends 'base.html' %}
{% block titulo %}
    Lista de usuarios
{% endblock %}
{% block contenido %}
    <div class="col-lg-6">
        <div class="card">
            <div class="card-title">
                <h4>Lista de usuarios </h4>
                <a href="{% url 'usuarios:crear_usuario' %}" class="btn btn-sm btn-primary "> Crear usuario</a>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>Username</th>
                            <th>Firt name</th>
                            <th>Last name</th>
                            <th>Email</th>
                            <th>Tipo usuario</th>
                            <th>Options</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for usuario in object_list %}
                            <tr>
                                <td>
                                    {{ usuario.id }}
                                </td>
                                <td>
                                    {{ usuario.username }}
                                </td>
                                <td>
                                    {{ usuario.first_name }}
                                </td>
                                <td>
                                    {{ usuario.last_name }}
                                </td>
                                <td>
                                    {{ usuario.is_staff |yesno:'Administrador,Cliente' }}
                                </td>
                                <td>
                                    {{ usuario.email }}
                                </td>

                                <td>
                                    <a href="{% url 'usuarios:actualizar_usuario' usuario.pk %}" class="btn btn-sm btn-info "> Editar </a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}